services:
  - type: web
    name: topotik-frontend
    runtime: static
    buildCommand: yarn build          # или npm run build
    staticPublishPath: build          # директория с результатом сборки
    routes:
      - type: rewrite
        source: /*
        destination: /index.html